projects:
  AmplifyAndroid:
    schemaPath: app\src\main\graphql\schema.json
    includes:
      - app\src\main\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app\src\main\graphql\com\amazonaws\amplify\generated\graphql
        graphQLApiId: zpsgoc3r6vfvxhvg6wk2ctzjbm
      endpoints:
        prod: >-
          https://saxdujmlezfm3irx64xfeudcb4.appsync-api.us-east-2.amazonaws.com/graphql
